import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Container from "@mui/material/Container";

// import '../styles/globals.css'

const Home: NextPage = () => {
  return (
    <Container maxWidth="sm">
      <h1>Home Page</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni consequatur ipsum ratione quasi, eveniet sed expedita nesciunt tempore odit obcaecati alias modi, deleniti repellendus architecto. Vel est deleniti nesciunt adipisci?
      Itaque id quisquam fuga libero. Vel, quod qui sit eius expedita deleniti ab earum et itaque, consectetur dolorem libero, eveniet consequatur. Sapiente, impedit. Veritatis eligendi sint cumque error repudiandae fugiat.
      Blanditiis nisi architecto molestias dolor ea aperiam fugit eaque. Nostrum voluptatem aperiam temporibus omnis accusantium exercitationem magni beatae laudantium, eos sit ratione laborum eveniet dolores veniam aliquid officiis obcaecati ullam?
      Aliquid sed eveniet illum modi pariatur sequi, similique excepturi aperiam ex impedit quisquam voluptates id atque reprehenderit maxime vero quaerat, nesciunt eum quia tempore tempora explicabo. Laboriosam ipsam repudiandae ratione.
      Quaerat odit, corrupti maxime cupiditate quibusdam eius illo alias ea temporibus blanditiis nulla repellat sit atque praesentium, consequatur sint magni! Voluptatibus nobis id deleniti ullam explicabo beatae similique iste quis!
      Impedit quia exercitationem accusamus rerum quod molestias nobis dolor, aperiam, placeat cupiditate facilis fuga dolore fugit provident earum! Explicabo, ut. Sed quaerat ullam obcaecati vel, cum voluptates sint exercitationem aliquid!
      Doloribus ducimus odio quia ab sapiente itaque autem repudiandae velit possimus, animi quidem saepe reiciendis consequuntur necessitatibus ipsum veritatis quo consequatur omnis praesentium earum. Tenetur assumenda consectetur sint fugiat laborum?
      Fugit tempore, dolor neque provident numquam dicta unde exercitationem sapiente expedita! Cupiditate quod libero tempora. Dignissimos perspiciatis quam culpa harum, sed beatae enim illum, inventore est natus vitae nisi repudiandae?
      Unde quis exercitationem eaque sit natus? Odio explicabo, mollitia ex praesentium animi corporis eum eius sunt iure ipsa totam sint? Sed, at explicabo eius sit repellat tenetur a nemo magnam?
      Dignissimos odit nesciunt architecto qui suscipit, voluptate pariatur officiis tempore earum blanditiis aliquid est quibusdam vero delectus eos sint obcaecati? Quam quisquam dolor nemo. Accusamus quisquam eaque mollitia deleniti cumque!
      Nostrum cupiditate optio dolorem. Animi dicta dolores, non obcaecati ullam consectetur molestiae impedit rerum. Labore quod voluptatem rerum recusandae, perferendis quo, mollitia quasi qui iusto fugiat accusamus magni molestias ipsum.
      Eaque beatae mollitia ducimus iste nesciunt voluptate, qui explicabo voluptates enim voluptatem maxime atque iure quasi itaque, quisquam sapiente consectetur autem ipsum. Quod incidunt, dolorem obcaecati repellendus temporibus porro fugit.
      Accusantium deleniti, laudantium adipisci cupiditate ex aspernatur hic eos nisi sit vitae culpa sunt nihil doloremque autem provident voluptates facilis distinctio earum fugiat voluptatum. Quod itaque dicta at vitae vel.
      Ad, maxime totam facere, in quaerat, enim sequi inventore laborum illum ipsam voluptate blanditiis consequuntur debitis sint adipisci voluptatem dolor animi ea soluta! Ducimus consequuntur totam alias modi! Nam, quisquam.
      Hic placeat eveniet necessitatibus fugiat repudiandae asperiores dolores natus explicabo sunt laboriosam sed perferendis quos nemo sequi, excepturi exercitationem ipsum. Earum expedita repudiandae dolore quae labore sit commodi quo minima.</p>
    </Container>
  )

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-center my-24 font-black tracking-tight text-6xl">Our homepage</h1>
        <h1 className={styles.title}>
          Learn <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
