version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - ${SERVER_PORT}:3000
      - 9255:9255
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - apinetwork
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:6.2.6
    networks:
      - apinetwork
  postgres:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    networks:
      - apinetwork
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  apinetwork:
volumes:
  pgdata:
