version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      # target: development
    volumes:
      - .:/app:delegated
      - /app/node_modules
      - /app/.next
    ports:
      - ${CLIENT_PORT}:3000
    command: npm run start
    stdin_open: true
    env_file:
      - .env
    networks:
      - storefrontnetwork
networks:
  storefrontnetwork:
